### ISSUE TITLE
merge schemas

### ISSUE THREAD

**Issue by hadfl** [maettu/Data-Processor#12]
for a project i need to merge different sub-schemas into one schema and then validate the whole of it.

would this be worth adding to the `Data::Processor` itself?

if so, i can generalise my code and add it as a merge method to `Data::Processor`

**Comment by maettu** [comment]
You should be able to build the schema data structure dynamically, before making the $processor.
Or would you want to merge two D::P objects?
I don't know if a merge method was worth coding..
Possibly you could make a test and / or show what you want to achieve?
I am certainly happy to merge cool functionality. :-)

**Comment by hadfl** [comment]
i get schemas dynamically from different worker objects. which i want to merge together to one schema.

but:
1. some schema elements might overlap but the validator points to a different validator. a merge makes sure that there will be a new (combined) validator.

2. an element might be optional for one schema, but mandatory for a second one. if you combine them the result will be optional instead of mandatory.

**Comment by hadfl** [comment]
here is a test: https://github.com/hadfl/Data-Processor/compare/merge

as you can see, two schemas specifying the validator for the same value differently. but ```schema_2``` overwrites the validator of ```$schema```, thus a value of 8 gives no error although it is wrong for ```$schema```...

a merge method would take care of overlapping elements, combining validators.

**Comment by maettu** [comment]
a patch will be welcome :-)

**Comment by hadfl** [comment]
--> https://github.com/maettu/Data-Processor/pull/13

i think this needs some serious review and more testing.
the pr shall be a basis for discussion

**Comment by maettu** [comment]
I am closing this for the moment. Feel free to re-open any time the discussion resumes.
