### ISSUE TITLE
Schema format documentation

### ISSUE THREAD

**Issue by draxil** [maettu/Data-Processor#18]
I found that for some elements of the schema definition (such as arrays) I had to read the actual code to figure them out. Would you accept a documentation patch to add some description to the POD? 

Posting this as an issue rather than a pull request to prompt myself to action later if you are agreeable to the idea!

**Comment by maettu** [comment]
Oops.. Sorry. Users should not have to read the code.

I will be glad to merge your documentation pull request, of course. :-)
Also, if you feel like correcting the English, or typos, or other enhancements, please do so.

**Comment by draxil** [comment]
I'm close to having a pull request for you. Although halfway through I
realised the documentation from your own internal schema descriptions would
probably have been half the battle?

Should get to finishing and sending sometime in the next few days in any
case.

**Comment by maettu** [comment]
closing as of https://github.com/maettu/Data-Processor/pull/19
