### ISSUE TITLE
wish: Allow validator to be a blessed object

### ISSUE THREAD

**Issue by tobyink** [maettu/Data-Processor#20]
Validators are currently allowed to be coderefs or regular expressions. Please add support for blessed objects. If the validator is a blessed object, make the following method call:

    $validator->validate($value)

It should return `undef` if valid, or an error message if there's a problem.

Rationale: MooseX::Types and Type::Tiny type constraints are objects which offer `validate` methods which work this way. So it will enable you to use them as drop-in validators for Data::Processor.

e.g.

    use Types::Standard -all;    

    # ... in schema ...
          foo => {
              validator => ArrayRef[Int],
              description => 'an arrayref of integers'
          },

**Comment by maettu** [comment]
Sounds good, thank you for your input.

**Comment by maettu** [comment]
This should be covered by dd868fd.
Please validate :-)

TODO: Documentation.

**Comment by maettu** [comment]
Docu done, thx @draxil 
test string updated as of comment by @tobyink 
released to CPAN as 1.0.2
