### ISSUE TITLE
Add an array option for members

### ISSUE THREAD

**Issue by hadfl** [maettu/Data-Processor#3]
it does not always make sense to use the ```regex``` option when having multiple items of the same type. an array option would be very helpful. e.g.:

```
my $schema = {
    section => {
        description => 'an array section',
	    array => 1,
        members => {
            foo => {
                # value restriction either with a regex..
                value => qr{f.*},
                description => 'a string beginning with "f"'
            },
            bar => {
                # ..or with a validator callback.
                validator => sub {
                    my $self   = shift;
                    my $parent = shift;
                    # undef is "no-error" -> success.
                    no strict 'refs';
                    return undef
                        if $self->{value} == 42;
                }
            },
            wuu => {
                optional => 1
            }
        }
    }
};
```
this would mean
```
my $data = {
    section => [
    	{
            foo => 'frobnicate',
            bar => 42,
       	    # "wuu" being optional, can be omitted..
    	},
	    {
       	    foo => 'frodo',
       	    bar => 42,
       	    wuu => 'I need wuu!',
	    },
    ],
};
```
instead of
```
my $data = {
    section => {
        i_have_no_meaning_but_i_need_to_be_here => {
            foo => 'frobnicate',
            bar => 42,
            # "wuu" being optional, can be omitted..
        },
        i_dont_know_what_i_am_doing_here_too => {
            foo => 'frodo',
            bar => 42, 
            wuu => 'I need wuu!',
        },
    },
};
```
when using the regex key option instead...

**Comment by hadfl** [comment]
--> https://github.com/maettu/Data-Processor/pull/4 should do it.

**Comment by maettu** [comment]
Thx. Thought about this but never got a round tuit.
Merged pull request; will have to review, though.
You are iterating over the array before you enter recursion, which is different from the way hashes are treated,
Also, I wonder if changes in quite a few places are necessary to make it happen.

**Comment by hadfl** [comment]
it was a nightly hack in a source i have seen for the first time, don't expect it to be the optimum.

basically, i was interested to get my example above working. then @oetiker asked for 'simplearray' support (validator and value) which i added afterwords...

**Comment by maettu** [comment]
This is completely fine. You are of course always welcome to add value. :-) If you drop me a note we will be able to coordinate and avoid merging.
I talked to @oetiker in the meantime.
